name: Build And Deploy
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: SSH server key setup
        run: |
          echo "${{ secrets.HOST_KEY }}" >> ~/.ssh/known_hosts
        shell: bash
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          scp -r ./dist/ ${{ secrets.DEPLOY_ENDPOINT }}
